# Generated by Django 2.2.6 on 2020-03-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'food',
            },
        ),
    ]
