# Generated by Django 2.2.6 on 2020-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
