# Generated by Django 2.2.6 on 2020-03-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
